### ISSUE TITLE
Add block quotes for where we are referencing upstream documentation

### ISSUE THREAD

**Issue by agracey** [suse-edge/suse-edge.github.io#120]
Each of the components is pulling content  from the upstream docs, these should be blockquoted.

**Comment by ranjinimn** [comment]
@agracey Can you please provide some information on proceeding with this issue?

**Comment by agracey** [comment]
For example, the text `Rancher is a powerful open-source Kubernetes management platform [...]` should be a block quote since we are pulling it from the Rancher documentation itself.

![image](https://github.com/user-attachments/assets/a38cc9a5-c200-45f3-8b74-be991c9dee10)
