### ISSUE TITLE
[doc] Issue in "Directory Structure" 

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#156]
Directory Structure:

https://suse-edge.github.io/atip-management-cluster.html#id-directory-structure

Missing `disable-embedded-capi.yaml` (as well as the content of the manifest) used later in the `install-dependencies.sh` script.

**Comment by agracey** [comment]
CC @alknopfler

**Comment by hardys** [comment]
Closed via https://github.com/suse-edge/suse-edge.github.io/pull/215
