### ISSUE TITLE
Missing titles for links in ATIP Automated Provisioning Documentation

### ISSUE THREAD

**Issue by fdegir** [suse-edge/suse-edge.github.io#162]
The two links in [ATIP Automated Provisioning with ZTP Documentation](https://suse-edge.github.io/atip-automated-provisioning.html) below are missing so opening this issue to ensure they are not missed. The text _???TITLE???_ denotes the missing titles.

* In [chapter 26.5](https://suse-edge.github.io/atip-automated-provisioning.html#ztp-add-advanced-network): The image generated using EIB has to include the network folder and the script following this section ([???TITLE???](https://suse-edge.github.io/atip-automated-provisioning.html#ztp-add-network-eib))
* In [chapter 26.6](https://suse-edge.github.io/atip-automated-provisioning.html#ztp-add-telco): The image generated using EIB has to include the specific Telco packages following this section ([???TITLE???](https://suse-edge.github.io/atip-automated-provisioning.html#ztp-add-telco-feature-eib))

**Comment by fdegir** [comment]
@hardys I wasn't sure what the titles for these things should be so I opened an issue instead of trying to guess what they may be and update them.

**Comment by hardys** [comment]
Thanks @fdegir I can take care of this
