### ISSUE TITLE
[doc] Issue in "Install Rancher"

### ISSUE THREAD

**Issue by avaleror** [suse-edge/suse-edge.github.io#165]
Install Rancher:

https://suse-edge.github.io/quickstart-elemental.html#id-install-rancher

We always refer to Rancher Project not to Rancher Prime, in this point we provide Rancher installation not Rancher's Prime. We should either provide the Rancher Prime Helm installation or at least make a note about it for customers. Also, instead of latest we should use the version that is supported in SUSE Edge actual release.

helm install rancher rancher-prime/rancher \
        --namespace cattle-system \
        --create-namespace \
        --set hostname="Hostname" \
        --set bootstrapPassword="WhaterverPassword" \
        --set replicas=1 \
        --version=2.8.1 \
        --set global.cattle.psp.enabled=false

**Comment by agracey** [comment]
I added a note instead. Please review #203
