### ISSUE TITLE
[doc] Issue in "SUSE Edge Documentation"

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/suse-edge.github.io#173]
SUSE Edge Documentation:

https://suse-edge.github.io/id-suse-edge-documentation.html#

"In this set of documentation": I'm sure that's proper English, but it just doesn't "sound right" to me. Maybe just leave it out and start with "You'll find quick starts [...]"?

**Comment by agracey** [comment]
Fixing in https://github.com/suse-edge/suse-edge.github.io/pull/196
