### ISSUE TITLE
[doc] Issue in "Components Used"

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/suse-edge.github.io#176]
Components Used:

https://suse-edge.github.io/id-suse-edge-documentation.html#id-components-used

We should definitely have a picture here, similar to
https://access.redhat.com/documentation/en-us/red_hat_device_edge/4/html-single/overview/index (Figure 1.1)

Also, let's be consistent with using Metal3 or Metal³.

Even with an image added, this list would benefit from sub-categories, e.g.

Management Stack
Operating System
Container Orchestration options
...

**Comment by agracey** [comment]
Fixed the metal^3^ issue (although I'm not a fan of how)
