### ISSUE TITLE
[doc] Metal3 quickstart Issue in "Prerequisites"

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/suse-edge.github.io#178]
Prerequisites:

https://suse-edge.github.io/quickstart-metal3.html#id-prerequisites

Without any further background, this section is a bit unclear. We're introducing the "Management cluster" for the first time without explaining what it is.

Maybe this gets easier once a diagram is added. But I'd still explain "Management cluster".

"control plane" as two words.

**Comment by hardys** [comment]
I'll close this one - please comment on #170 if you think it still needs improvement after the diagram is added for context

**Comment by hardys** [comment]
Actually I'll reopen and we can track resolution via #170
