### ISSUE TITLE
[doc] orphaned Prerequisites section

### ISSUE THREAD

**Issue by dariavladykina** [suse-edge/suse-edge.github.io#188]
File: asciidoc/quickstart/eib.adoc

[This section](https://suse-edge.github.io/quickstart-eib.html#id-prerequisites-2) is orphaned as a single top-level item. I believe the entire structure must be updated to make several same-level chapters (e.g. Prerequisites, Getting the EIB image, Creating the image configuration directory, and so on) with their respective subordinate sections.

**Comment by agracey** [comment]
I moved everything down a level to where I think it flows better
