### ISSUE TITLE
[doc] Duplicated text in "Generating the downstream image using EIB"

### ISSUE THREAD

**Issue by dariavladykina** [suse-edge/suse-edge.github.io#190]
File: asciidoc/product/atip-automated-provision.adoc

 In `[this section](https://suse-edge.github.io/atip-automated-provisioning.html#ztp-eib-edge-image)`, the full paragraph starting with:
_In the network folder, the configure-network.sh file contains the networking configuration for the downstream cluster. [...]_

seems duplicated the the following paragraph after the screen.

**Comment by hardys** [comment]
Closed via https://github.com/suse-edge/suse-edge.github.io/pull/215
