### ISSUE TITLE
[doc] Please rephrase the text in "Manual installation"

### ISSUE THREAD

**Issue by dariavladykina** [suse-edge/suse-edge.github.io#195]
File: asciidoc/integrations/nvidia-slemicro.adoc

In [this section](https://suse-edge.github.io/id-nvidia-gpus-on-sle-micro.html#id-manual-installation), the first sentence better be rephrased for clarity:

Therefore, we recommend that you not only ensure that the driver version that you are selecting is compatible with your GPU and meets any CUDA requirements that you may have by checking the [CUDA release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/), but also to check that the driver version that you plan on deploying has a matching version in the [NVIDIA SLE15-SP5 repository](http://download.nvidia.com/suse/sle15sp5/x86_64/) to ensure that you have equivalent package versions for the supporting components available. To find the NVIDIA open-driver versions, search the SUSE Customer Center for the "nvidia-open-driver" in [SLE Micro 5.5 for x86_64](https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Micro&version=5.5&arch=x86_64). Here, you will see four versions available, with 545.29.06 being the newest:

**Comment by agracey** [comment]
I'm not sold on the way I rewrote this in #203

**Comment by agracey** [comment]
@dariavladykina Could you close this issue if you feel like my change is good enough?
