### ISSUE TITLE
[doc] Issue in "SUPPORTED COMPONENT VERSIONS"

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/suse-edge.github.io#198]
SUPPORTED COMPONENT VERSIONS:

https://suse-edge.github.io/id-appendix.html#id-1.8.2.2

Given that the SKU contains SUSE Manager, shouldn't this table contain SUSE Manager? If yes, what version is officially supported?

**Comment by agracey** [comment]
Yes, and good question. CC @rdoxenham
