### ISSUE TITLE
[doc] Issue in "Installing cluster API dependencies"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#217]
Installing cluster API dependencies:

https://suse-edge.github.io/quickstart-metal3.html#id-installing-cluster-api-dependencies

Why do we use a hidden directory ``~/.cluster-api` for CAPI manifest? 
 
Does `clusterctl` need the directory for something runtime?

**Comment by hardys** [comment]
@peteingithub yes the `~/.cluster-api/clusterctl.yaml` is the configuration file consumed by `clusterctl` - we configure it to use the downstream SUSE images, without this it'll pull the upstream images which we do not test/support.

**Comment by hardys** [comment]
Let me know if you think any additional clarification is needed to the docs or if this can be closed, thanks!

**Comment by peteingithub** [comment]
I did not spot this configuration file in the CAPI docs, so that's the reason I asked.  

If the configuration file would only be used once, then it is OK to close.

**Comment by peteingithub** [comment]
OK, I was confused for the directory being hidden under user's home directory `~/.cluster-api` while the clusterctl docs state it residing in `$XDG_CONFIG_HOME`, which is missing in our management cluster, and path then defaulting to `$HOME/.config`. But it seems the EIB docs state the path as command line parameter pointing to `/home/metal3/clusterctl.yml`.
