### ISSUE TITLE
[doc] Metal3 quickstart clarify "Disabling TLS for virtualmedia ISO attachment"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#220]
Disabling TLS for virtualmedia ISO attachment:

https://suse-edge.github.io/quickstart-metal3.html#id-disabling-tls-for-virtualmedia-iso-attachment

Maybe add instructions how to configure the cluster with external ironic-vmedia-cert.

**Comment by hardys** [comment]
Thanks for the feedback @peteingithub!

I'll try to make this clearer, but the alternative solution isn't related to configuring the cluster, you have to copy the CA cert from `kubectl get secret -n metal3-system ironic-vmedia-cert -o yaml` and configure the server BMC to trust it - the exact steps for that depend on the server vendor (and it's not possible at all with some, SuperMicro for example)

Suggestions on how to make that clearer are welcome but I'll take this issue and try to clarify
