### ISSUE TITLE
[doc] Issue in "Build the installation media"

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/suse-edge.github.io#255]
Build the installation media:

https://documentation.suse.com/suse-edge/3.0/html/edge/quickstart-elemental.html#build-installation-media

IIRC we need to put GM2 there and the device to write into as well otherwise the installation will just wait for user input.

**Comment by ranjinimn** [comment]
@e-minguez Can you please provide the code  and other relevant information to add GM2 and the device?

**Comment by e-minguez** [comment]
> @e-minguez Can you please provide the code  and other relevant information to add GM2 and the device? 

Unfortunately I'm not available until mid September 😅 Can you ping someone else in the meantime for this and other issues? Thanks
