### ISSUE TITLE
[doc] Issue in "Install Rancher"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#279]
Install Rancher:

https://suse-edge.github.io/quickstart-elemental.html#install-rancher

Maybe set the versions for Cert-Manager and Rancher. Otherwise the latest would be deployed.

**Comment by hardys** [comment]
It looks like https://github.com/rancher/rancher-docs/pull/924 removed the pin for cert-manager in the Rancher docs, so we should probably align with that, but yes we should specify the Rancher version
