### ISSUE TITLE
[doc] Issue in "Downstream cluster upgrades"

### ISSUE THREAD

**Issue by ipetrov117** [suse-edge/suse-edge.github.io#301]
Downstream cluster upgrades:

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-lifecycle.html#id-downstream-cluster-upgrades

"Change the block RKE2ControlPlane in the capi-provisioning-example.yaml shown in the following [section](https://documentation.suse.com/suse-edge/3.0/html/edge/atip-automated-provisioning.xml#single-node-provision):"

Broken link.

**Comment by ranjinimn** [comment]
Taking this issue for this week's documentation - 08/19-08/23

**Comment by ranjinimn** [comment]
@alknopfler I see that all the 3 links are broken in this section. Can you please let me know to which of the sections and references you want me to redirect the user?
