### ISSUE TITLE
[doc] Issue in "About"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#313]
About:

https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html#id-about

Version bump needed here?

**Comment by ranjinimn** [comment]
@peteingithub The section "About: Release Notes is an overview of what is expected there. Can you please let me know what version are you looking for?

**Comment by peteingithub** [comment]
Do we not support newer versions of Kubernetes and Rancher already?

**Comment by ranjinimn** [comment]
@atanasdinov  Can you please let me know the version information that we can include for Kubernetes and Rancher?

**Comment by atanasdinov** [comment]
I don't really understand the question. We properly list the supported versions with latest being k3s / RKE2 v1.28.10 on Rancher v2.8.5 in [Edge 3.0.2](https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html#id-release-3-0-2).

**Comment by ranjinimn** [comment]
@peteingithub The following information is available in the section: https://documentation.suse.com/suse-edge/3.0/single-html/edge/#id-release-3-0-2

- K3s - 1.28.10
- RKE2 -  1.28.10
- Rancher Prime - 2.8.5

We are going to restructure the document for 3.0.2 to reflect first. 

Let me know if you are looking at any additional information.

**Comment by peteingithub** [comment]
@atanasdinov 
I see, my bad. The newer version is downwards. 
Thoughts about the newest being listed first? I have seen such, and even if it is not the "correct" way it's the most usable and easiest.

**Comment by ranjinimn** [comment]
@peteingithub Yes, that's the plan as mentioned earlier.
