### ISSUE TITLE
[doc] Issue in "Installation"

### ISSUE THREAD

**Issue by gusraggio** [suse-edge/suse-edge.github.io#338]
Installation:

https://documentation.suse.com/suse-edge/3.0/html/edge/components-kubevirt.html#id-installation-4

"Rancher Dashboard Extension section" https://documentation.suse.com/suse-edge/3.0/html/edge/rancher-dashboard-extensions.xml NOT FOUND

**Comment by ranjinimn** [comment]
This issue was addressed as part of PR#341
