### ISSUE TITLE
[doc] Issue in "Management cluster definition file" - Is git needed?

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#342]
Management cluster definition file:

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-management-cluster.html#mgmt-cluster-image-definition-file

Is package `git` used for something within the management cluster?

**Comment by ranjinimn** [comment]
@alknopfler Can you please give me information to proceed with this request?

**Comment by peteingithub** [comment]
In the packages list there were 
```- jq
- git```
I was asking about git being a required package. It now seems to be removed.
