### ISSUE TITLE
[doc] Issue in "Downstream cluster provisioning with Direct network provisioning (single-node)" - typo

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#346]
Downstream cluster provisioning with Direct network provisioning (single-node):

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-automated-provisioning.html#single-node

`There are two different steps to automate the provisioning of a single-node downstream cluster using **directed** network provisioning:`
-> 
`There are two different steps to automate the provisioning of a single-node downstream cluster using **direct** network provisioning:`

**Comment by hardys** [comment]
Related to https://github.com/suse-edge/suse-edge.github.io/issues/350 - it's not a typo, the intention is to align with the "directed network provisioning" term ref https://github.com/suse-edge/suse-edge.github.io/pull/354

**Comment by peteingithub** [comment]
OK, my bad.
