### ISSUE TITLE
[doc] Issue in "Downstream cluster provisioning in air-gapped scenarios" - typo

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#350]
Downstream cluster provisioning in air-gapped scenarios:

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-automated-provisioning.html#airgap-deployment

"The **directed** network provisioning"
-> 
"The **direct** network provisioning "

**Comment by hardys** [comment]
Actually after discussion related to #267 we agreed to stick with "Directed network provisioning" but it seems we've not applied that change consistently as there are still a few references to "Direct network provisioning" - I'll push a PR to align the naming, thanks!
