### ISSUE TITLE
[doc] Issue in "Downstream cluster provisioning with Direct network provisioning (multi-node)" - typo

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#359]
Downstream cluster provisioning with Direct network provisioning (multi-node):

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-automated-provisioning.html#multi-node

"Provision step
Once the three **bar metal** hosts are enrolled and available, the next step is to provision the **bare-metal** hosts..."
->  
baremetal

**Comment by ranjinimn** [comment]
Fixed in #363
