### ISSUE TITLE
[doc] Issue in "Components Versions"

### ISSUE THREAD

**Issue by timirnich** [suse-edge/suse-edge.github.io#361]
Components Versions:

https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html#id-components-versions-3

Add an explanation what entries being boldfaced means. I'm assuming it means the component version has changed but this isn't explicitly mentioned anywhere as far as I can see.

**Comment by hardys** [comment]
This was fixed via https://github.com/suse-edge/suse-edge.github.io/pull/364
