### ISSUE TITLE
[doc] Issue in "Prerequisites"

### ISSUE THREAD

**Issue by joesusecom** [suse-edge/suse-edge.github.io#365]
Prerequisites:

https://documentation.suse.com/suse-edge/3.0/html/edge/quickstart-eib.html#id-prerequisites-2

The image should have "GM" in the name, not "GM2". This was probably changed on the BCL side after the Edge 3.0 docs were released.

**Comment by joesusecom** [comment]
Just double-checked. The Self-Install ISO is indeed named "GM2". May still require clarification because EIB can also use the RAW images that have "GM" in the name.

**Comment by hardys** [comment]
Thanks @joesusecom indeed the GM2 was a respin after the initial release, but it contains fixes which we need (the respin was requested for the edge use-case), so the docs are correct, users should pick the GM2 version.

From a quick grep we can see there is one mistake where the original GM version is still referenced:

```
grep -R SLE-Micro.x86_64-5.5.0-Default | grep -v build | grep iso | grep -v GM2
./quickstart/elemental.adoc:    baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
```

All of the raw image references correctly reference the "GM" version AFAICS, so I think if we fix the above issue this can be closed.
