### ISSUE TITLE
[doc] Nit in "Bug & Security Fixes"

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/suse-edge.github.io#377]
Bug & Security Fixes:

https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html#id-bug-security-fixes-3

`The Metal3 chart fixes an issue where host reprovisioning may use stale static static network configuration: [SUSE Edge issue #133](https://github.com/suse-edge/charts/pull/133)`

Double "static"

**Comment by hardys** [comment]
Closed via #405
