### ISSUE TITLE
[RFE] SL Micro 6 doesn't allow ssh with password for root user by default (SLE Micro 5.5 does)

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/suse-edge.github.io#383]
We probably would like to add a small note on the release notes for Edge 3.1 about this.

**Comment by atanasdinov** [comment]
Also look up all `ssh` references in the docs - we might have to adjust EIB definitions to user non-root users.

**Comment by e-minguez** [comment]
SL Micro 6 release notes are going to be updated to reflect those changes as well https://bugzilla.suse.com/show_bug.cgi?id=1230781
