### ISSUE TITLE
[doc] Issue in "Management cluster definition file" - Initializer automatically set?

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#396]
Management cluster definition file:

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-management-cluster.html#mgmt-cluster-image-definition-file

```
Note
The names of the nodes must be unique in the cluster, and the initializer field must be set to true for the first node in the list. 
```

I'm assuming the EIB code handles the case where initializer is not set, the first one would be selected as the initializer.

**Comment by hardys** [comment]
This was resolved by https://github.com/suse-edge/suse-edge.github.io/pull/373 - I'll create a backport

**Comment by hardys** [comment]
Closed via https://github.com/suse-edge/suse-edge.github.io/pull/416
