### ISSUE TITLE
[doc] Issue in "Installing the Endpoint Copier Operator"

### ISSUE THREAD

**Issue by dannysauer** [suse-edge/suse-edge.github.io#408]
Installing the Endpoint Copier Operator:

https://documentation.suse.com/suse-edge/3.0/html/edge/guides-metallb-kubernetes.html#id-installing-the-endpoint-copier-operator

The endpoint copier operator requires you to have pre-created the service the operator will manage.  While I agree that it probably _should_ be done by the helm chart since the name is essentially hard-coded in the operator the chart installs, that is not currently the case. :)  So maybe include the command necessary to generate the kubernetes-vip service.

https://github.com/suse-edge/endpoint-copier-operator?tab=readme-ov-file#running-on-the-cluster

**Comment by e-minguez** [comment]
The main branch already includes this https://github.com/suse-edge/suse-edge.github.io/blob/main/asciidoc/guides/metallb-kube-api.adoc#installing-the-endpoint-copier-operator, I guess it is a matter of backporting the instructions to the 3.0 branch.

**Comment by hardys** [comment]
Closed via #420
