### ISSUE TITLE
[doc] Issue in "BMC automated deployments with Metal3" - 'bare-metal

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#427]
BMC automated deployments with Metal3:

https://documentation.suse.com/suse-edge/3.0/html/edge/quickstart-metal3.html#

Looks like the term is used interchangeably.  Should we pick one?

**Comment by hardys** [comment]
AFAICS we're using "bare-metal" for generic references and "BareMetalHost" where we're referring to the BMH itself (where the CRD name shouldn't be hyphenated) - can you see any specific inconsistencies we should be addressing here?

**Comment by peteingithub** [comment]
The only ones left would be in the text at 
https://documentation.suse.com/suse-edge/3.0/html/edge/id-suse-edge-documentation.html#id-directed-network-provisioning
and in the graph at
https://documentation.suse.com/suse-edge/3.0/html/edge/atip-architecture.html#id-atip-architecture
